# Generated by Django 5.2.12 on 2026-03-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_merchandising'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_qty',
            field=models.PositiveIntegerField(default=1, help_text='Minimum order quantity for this item.'),
        ),
    ]
