# Generated by Django 5.2.12 on 2026-03-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_rating_product_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='GST percentage for this product (e.g., 18.00).', max_digits=5),
        ),
    ]
