# Generated by Django 5.2.12 on 2026-04-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_is_returnable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters (optional).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams (optional).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in centimeters (optional).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override: height in centimeters (optional).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override: weight in grams (optional).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override: width in centimeters (optional).', max_digits=10, null=True),
        ),
    ]
