# Generated by Django 5.2.12 on 2026-05-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_height_cm_product_weight_g_product_width_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_custom_courier',
            field=models.BooleanField(default=False, help_text='Allow customers to choose custom courier service at checkout.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_doorstep_delivery',
            field=models.BooleanField(default=False, help_text='Allow customers to choose doorstep delivery at checkout.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_store_pickup',
            field=models.BooleanField(default=True, help_text='Allow customers to choose direct store pickup at checkout.'),
        ),
    ]
