# Generated by Codex on 2026-05-15

from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_sitesettings_enable_custom_courier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gst_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=18.0,
                help_text="GST percentage added to this product's price for storefront MRP (e.g., 18.00).",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leave blank to use the base product price. GST is added for storefront MRP.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="hsn_code",
            field=models.CharField(
                default="000000",
                help_text="Required. Enter numbers only.",
                max_length=16,
                validators=[
                    RegexValidator(
                        regex="^\\d+$",
                        message="HSN code must contain numbers only.",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
