# Generated by Django 5.2.12 on 2026-03-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for design rejection.'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='custom_design_file',
            field=models.FileField(blank=True, help_text='Uploaded JPG, PNG, or PDF for bespoke orders.', null=True, upload_to='custom_designs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review (Bespoke Design)'), ('design_approved', 'Design Approved, Pending Payment'), ('design_rejected', 'Design Rejected'), ('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=32),
        ),
    ]
