# Generated by Django 5.2.12 on 2026-03-29 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_bulkquoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkquoterequest',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bulkquoterequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_quote', to='orders.order'),
        ),
        migrations.AddField(
            model_name='bulkquoterequest',
            name='quoted_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bulkquoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
