# Generated by Django 5.2.12 on 2026-03-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_cgst_amount_order_gst_amount_order_sgst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_bulk',
            field=models.BooleanField(default=False, help_text='True if order was created via Bulk Quote.'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, help_text='Modern alphanumeric ID (e.g., JFPA-X7K94-ML)', max_length=50, unique=False),
        ),
    ]
