# Generated by Django 5.2.12 on 2026-03-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, help_text='Modern alphanumeric ID (e.g., JFPA-X7K94-ML)', max_length=50, unique=True),
        ),
    ]
