# Generated by Django 5.2.12 on 2026-03-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Courier AWB or Tracking Number', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_provider',
            field=models.CharField(blank=True, help_text='e.g., Shiprocket, Delhivery, BlueDart', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Direct link to track the package', max_length=500),
        ),
    ]
