# Generated by Django 5.2.12 on 2026-04-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_tracking_number_order_tracking_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, help_text='Modern alphanumeric ID (e.g., JFPA-X7K94-ML)', max_length=50, unique=True, verbose_name='Order ID'),
        ),
    ]
