# Generated by Django 5.2.12 on 2026-04-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkquoterequest',
            name='quoted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when admin sent the price quote to the customer.', null=True),
        ),
    ]
