# Generated by Django 5.2.12 on 2026-04-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_add_quoted_at_to_bulkquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_pdf',
            field=models.FileField(blank=True, help_text='Upload official GST Invoice PDF here. This will be emailed to the customer.', null=True, upload_to='invoices/%Y/%m/'),
        ),
    ]
