# Generated by Django 5.2.12 on 2026-04-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_invoice_emailed_order_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_gst_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='is_business_order',
            field=models.BooleanField(db_index=True, default=False, help_text='True if customer placed this order as a business (GST invoice).'),
        ),
    ]
