# Generated by Django 5.2.12 on 2026-04-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review (Bespoke Design)'), ('design_approved', 'Design Approved, Pending Payment'), ('design_rejected', 'Design Rejected'), ('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('ready_for_pickup', 'Ready for pickup'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=32),
        ),
    ]
