# Generated by Django 5.2.12 on 2026-03-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_design_file',
            field=models.FileField(blank=True, help_text='Uploaded JPG, PNG, or PDF for bespoke orders.', null=True, upload_to='cart_designs/%Y/%m/'),
        ),
    ]
