# Generated by Django 5.2.12 on 2026-03-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='abandoned_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
