# Generated by Django 5.2.12 on 2026-04-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_price_at_add'),
        ('catalog', '0007_product_is_returnable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Selected color/size variant, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='catalog.productvariant'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price_at_add',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Effective price (variant or base) at the time the item was added.', max_digits=12, null=True),
        ),
    ]
