# Generated by Django 5.2.12 on 2026-06-27 17:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(help_text="Employee code (e.g. JFP001) or 'Admin' or 'System'", max_length=200)),
                ('action', models.CharField(help_text='e.g. PUNCH_IN, EDIT_ATTENDANCE', max_length=100)),
                ('table_name', models.CharField(blank=True, max_length=100)),
                ('record_id', models.PositiveIntegerField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(editable=False, help_text='Auto-generated. Format: JFP001, JFP002 …', max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily Wage'), ('hourly', 'Hourly')], default='monthly', max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, help_text='Base salary amount (₹). Interpretation depends on salary_type.', max_digits=10)),
                ('pin_hash', models.CharField(help_text='Hashed PIN (never store raw)', max_length=256)),
                ('profile_photo', models.CharField(blank=True, help_text='Cloudinary URL or local media URL', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='OfficeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(default='Jai Fancy Packs', max_length=200)),
                ('latitude', models.FloatField(default=0.0, help_text='Office GPS latitude')),
                ('longitude', models.FloatField(default=0.0, help_text='Office GPS longitude')),
                ('allowed_radius_meters', models.PositiveIntegerField(default=100, help_text='Geofence radius in metres. Employee must be within this distance to punch.')),
                ('shift_start', models.TimeField(default=datetime.time(10, 0), help_text='10:00 AM')),
                ('shift_end', models.TimeField(default=datetime.time(19, 45), help_text='7:45 PM')),
                ('late_grace_minutes', models.PositiveIntegerField(default=10, help_text='Minutes after shift_start before punch-in is marked LATE.')),
                ('half_day_cutoff', models.TimeField(default=datetime.time(15, 0), help_text='Punch-out before this time → HALF_DAY.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Office Settings',
                'verbose_name_plural': 'Office Settings',
            },
        ),
        migrations.CreateModel(
            name='RegisteredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(help_text='Browser-generated fingerprint hash', max_length=256, unique=True)),
                ('device_name', models.CharField(max_length=200)),
                ('browser', models.CharField(blank=True, max_length=200)),
                ('os', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('registered_for', models.ForeignKey(blank=True, help_text='Employee this device belongs to (optional — shared devices leave blank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_devices', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Registered Device',
                'verbose_name_plural': 'Registered Devices',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily Wage'), ('hourly', 'Hourly')], max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Salary History',
                'verbose_name_plural': 'Salary History',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('punch_in', models.DateTimeField(blank=True, null=True)),
                ('punch_out', models.DateTimeField(blank=True, null=True)),
                ('working_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('INCOMPLETE', 'Incomplete')], default='ABSENT', max_length=20)),
                ('leave_deduction', models.DecimalField(decimal_places=1, default=0, help_text='0 = present, 0.5 = half day, 1.0 = full absent', max_digits=3)),
                ('punch_in_photo', models.CharField(blank=True, max_length=500)),
                ('punch_out_photo', models.CharField(blank=True, max_length=500)),
                ('punch_in_latitude', models.FloatField(blank=True, null=True)),
                ('punch_in_longitude', models.FloatField(blank=True, null=True)),
                ('punch_in_accuracy', models.FloatField(blank=True, help_text='GPS accuracy in metres', null=True)),
                ('punch_out_latitude', models.FloatField(blank=True, null=True)),
                ('punch_out_longitude', models.FloatField(blank=True, null=True)),
                ('punch_out_accuracy', models.FloatField(blank=True, null=True)),
                ('distance_from_office', models.FloatField(blank=True, help_text='Metres from office at punch-in', null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=256)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('browser', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_manual_entry', models.BooleanField(default=False)),
                ('manual_entry_note', models.TextField(blank=True, help_text='Required when is_manual_entry=True')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'employee__employee_code'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Calendar year, e.g. 2025')),
                ('carry_forward', models.DecimalField(decimal_places=1, default=0, help_text='Unused leaves carried from previous year', max_digits=5)),
                ('credited', models.DecimalField(decimal_places=1, default=0, help_text='Leaves earned this year (max 12)', max_digits=5)),
                ('used', models.DecimalField(decimal_places=1, default=0, help_text='Leaves consumed (deducted from attendance)', max_digits=5)),
                ('last_credit_date', models.DateField(blank=True, help_text='Date of most recent monthly leave credit', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'ordering': ['-year'],
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('FULL', 'Full Day'), ('HALF', 'Half Day')], default='FULL', max_length=10)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Leave Record',
                'verbose_name_plural': 'Leave Records',
                'ordering': ['-leave_date'],
                'unique_together': {('employee', 'leave_date')},
            },
        ),
    ]
