# Generated by Django 5.2.12 on 2026-06-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive failed PIN attempts'),
        ),
        migrations.AddField(
            model_name='employee',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Account lock expiry time', null=True),
        ),
    ]
