# Generated by Django 5.2.12 on 2026-03-29 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount (INR)'), ('percent', 'Percentage (%)')], default='fixed', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Amount or Percentage value.', max_digits=10)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order subtotal to apply this coupon.', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='For percentage discounts, the maximum amount that can be deducted.', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total times this can be used.', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
    ]
